accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns=[
    path('login/', views.login_user, name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('register/', views.create_user, name='register'),
]

pollme/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from django.core.mail import send_mail 

urlpatterns = [
    path('', views.home, name='home'),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace="accounts")),
    path('polls/', include('polls.urls', namespace="polls")),
]

# def send_email_to_clint():
#     subject = 'Thank you for registering to our site'
#     message = ' it  means a world to us '
#     email_from = settings.EMAIL_HOST_USER
#     recipient_list = ['mangasuler@gmail.com']
#     send_mail( subject, message, email_from, recipient_list )

polls/urls.py
from django.urls import path
from . import views

app_name = "polls"

urlpatterns = [
    path('list/', views.polls_list, name='list'),
    path('list/user/', views.list_by_user, name='list_by_user'),
    path('add/', views.polls_add, name='add'),
    path('edit/<int:poll_id>/', views.polls_edit, name='edit'),
    path('delete/<int:poll_id>/', views.polls_delete, name='delete_poll'),
    path('end/<int:poll_id>/', views.end_poll, name='end_poll'),
    path('edit/<int:poll_id>/choice/add/', views.add_choice, name='add_choice'),
    path('edit/choice/<int:choice_id>/', views.choice_edit, name='choice_edit'),
    path('delete/choice/<int:choice_id>/',
         views.choice_delete, name='choice_delete'),
    path('<int:poll_id>/', views.poll_detail, name='detail'),
    path('<int:poll_id>/vote/', views.poll_vote, name='vote'),
]

templates/includes/navbar.html
<nav class="navbar navbar-expand-sm navbar-light bg-light mb-5">
    <a class="navbar-brand" href="{% url 'home' %}"><i class="fas fa-person-booth"></i></a>
    <button class="navbar-toggler d-lg-none" type="button" data-toggle="collapse" data-target="#collapsibleNavId"
        aria-controls="collapsibleNavId" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="collapsibleNavId">
        <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'home' %}">Home <span class="sr-only">(current)</span></a>
            </li>
            {% if request.user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'polls:list' %}">Polls</a>
            </li>
            {% endif %}
        </ul>
        <div class="navbar-nav ml-auto">
            {% if request.user.is_authenticated %}
            <a class="nav-link" href="{% url 'polls:list_by_user' %}">My Polls</a>
            <a class="nav-link" href="{% url 'accounts:logout' %}">Logout</a>
            {% else %}
            <a class="nav-link" href="{% url 'accounts:login' %}">Login</a>
            <a class="nav-link" href="{% url 'accounts:register' %}">Register</a>
            {% endif %}
        </div>
    </div>
</nav>